"""Phase 4 Review Tasks

Revision ID: 45971fa6f67f
Revises: 0002_phase3_rag_foundation
Create Date: 2026-10-04 00:14:50.864862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45971fa6f67f'
down_revision = '0002_phase3_rag_foundation'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_tasks',
    sa.Column('task_id', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['adverse_events.event_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('review_decisions',
    sa.Column('decision_id', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=False),
    sa.Column('reviewer_id', sa.String(length=50), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['review_tasks.task_id'], ),
    sa.PrimaryKeyConstraint('decision_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_decisions')
    op.drop_table('review_tasks')
    # ### end Alembic commands ###
