"""feat(phase9): add telemetry tables

Revision ID: d5a180fcf181
Revises: 45971fa6f67f
Create Date: 2026-10-04 13:01:51.866715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a180fcf181'
down_revision = '45971fa6f67f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runtime_traces',
    sa.Column('trace_id', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('latency_sec', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('app_version', sa.String(length=20), nullable=False),
    sa.Column('workflow_version', sa.String(length=20), nullable=False),
    sa.Column('dataset_version', sa.String(length=20), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('trace_id')
    )
    op.create_table('runtime_events',
    sa.Column('event_id', sa.String(length=50), nullable=False),
    sa.Column('trace_id', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('node_name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('latency_sec', sa.Float(), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('tool_version', sa.String(length=20), nullable=True),
    sa.Column('model_name', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('index_version', sa.String(length=20), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('event_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['runtime_traces.trace_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.drop_index('ix_document_chunks_compound_id', table_name='document_chunks')
    op.drop_index('ix_document_chunks_content_hash', table_name='document_chunks')
    op.drop_index('ix_document_chunks_doc_id', table_name='document_chunks')
    op.drop_index('ix_document_chunks_doc_type', table_name='document_chunks')
    op.drop_index('ix_document_chunks_index_version', table_name='document_chunks')
    op.drop_index('ix_document_chunks_trial_id', table_name='document_chunks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_document_chunks_trial_id', 'document_chunks', ['trial_id'], unique=False)
    op.create_index('ix_document_chunks_index_version', 'document_chunks', ['index_version'], unique=False)
    op.create_index('ix_document_chunks_doc_type', 'document_chunks', ['doc_type'], unique=False)
    op.create_index('ix_document_chunks_doc_id', 'document_chunks', ['doc_id'], unique=False)
    op.create_index('ix_document_chunks_content_hash', 'document_chunks', ['content_hash'], unique=False)
    op.create_index('ix_document_chunks_compound_id', 'document_chunks', ['compound_id'], unique=False)
    op.drop_table('runtime_events')
    op.drop_table('runtime_traces')
    # ### end Alembic commands ###
